# Generated by Django 4.1.6 on 2023-02-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_image_user_pofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pofile_image',
            new_name='profile_image',
        ),
    ]
