# Generated by Django 4.1.6 on 2023-03-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('women', 'women'), ('men', 'men'), ('another', 'another')], default='another', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
