# Generated by Django 4.1.6 on 2023-03-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_gender_alter_user_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('women', 'women'), ('men', 'men'), ('another', 'another')], default='another', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
